### ISSUE TITLE
Mistake in description of Diffraction Stacking Localisation tutorial

### ISSUE THREAD

**Issue by mrava87** [FraCSPy/FraCSPy#54]
In the Diffraction Stacking Localisation tutorial we say `The input data waveforms are computed with the help of PyLops operator which involves finite-difference (FD) modelling`, however the PyLops's Kirchoff operator is used for modelling, which does not use FD, instead a Kirchoff integral relation with high-frequency Green's functions.

**Comment by mrava87** [comment]
And the same text appears in Diffraction Stacking Localisation With Moment Tensor Inversion, which i guess in this case should refer to SOFI3D as it seems you use that data as input

**Comment by danikiev** [comment]
@mrava87 

Thanks, will take care of that!
